rm -f Berrycurvature-norm -falized.dat
rm -f Berrycurvature-norm -falized.gnu
rm -f Berrycurvature.dat
rm -f Berrycurvature.gnu
rm -f POSCAR-rotated
rm -f SPOSCAR
rm -f WT.out
rm -f arc.dat_bulk
rm -f arc.dat_l
rm -f arc.dat_r
rm -f arc_bulk.gnu
rm -f arc_l.gnu
rm -f arc_l.png
rm -f arc_l_only.gnu
rm -f arc_r.gnu
rm -f arc_r_only.gnu
rm -f bulkband-phonon.agr
rm -f bulkband-phonon.eps
rm -f bulkek-loto.eps
rm -f bulkek-noloto.eps
rm -f bulkek.dat
rm -f bulkek.eps
rm -f bulkek.gnu
rm -f dos.dat_bulk
rm -f dos.dat_l
rm -f dos.dat_r
rm -f fort.8
rm -f phonopy.yaml
rm -f phonopyTB_hr.dat
rm -f slabek.dat
rm -f slabek.gnu
rm -f slabek.png
rm -f surfdos_bulk.gnu
rm -f surfdos_l-noloto.png
rm -f surfdos_l.gnu
rm -f surfdos_l.png
rm -f surfdos_l_only.gnu
rm -f surfdos_r.gnu
rm -f surfdos_r.png
rm -f surfdos_r_only.gnu
rm -f wanniercenter3D_Weyl.dat
rm -f wanniercenter3D_Weyl_1.eps
rm -f wanniercenter3D_Weyl_1.gnu
rm -f wanniercenter3D_Weyl_1.gnu-bak
rm -f wcc.dat
rm -f wcc.gnu
