#!/bin/bash
rm -f    Bi2Se3.cif
rm -f    FS3D.bxsf
rm -f    GapCube.dat
rm -f    GapCube.gnu
rm -f    GapPlane.dat
rm -f    GapPlane.gnu
rm -f    GapPlane_matlab.dat
rm -f    POSCAR-rotated
rm -f    WT.out
rm -f    arc.dat_bulk
rm -f    arc.dat_l
rm -f    arc.dat_r
rm -f    arc.jdat_l
rm -f    arc.jdat_r
rm -f    arc.jsdat_l
rm -f    arc.jsdat_r
rm -f    arc_bulk.gnu
rm -f    arc_l.gnu
rm -f    arc_l.png
rm -f    arc_l_jdos.gnu
rm -f    arc_l_jdos.png
rm -f    arc_l_jsdos.gnu
rm -f    arc_l_jsdos.png
rm -f    arc_r.gnu
rm -f    arc_r_jdos.gnu
rm -f    arc_r_jsdos.gnu
rm -f    bulkek-pointsmode.dat
rm -f    bulkek*
rm -f    dos.dat
rm -f    dos.dat_bulk
rm -f    dos.dat_l
rm -f    dos.dat_r
rm -f    dos.gnu
rm -f    dos.jdat_l
rm -f    dos.jdat_r
rm -f    gap2d.dat
rm -f    input.dat-old
rm -f    psi_abs.txt
rm -f    ribbonek.dat
rm -f    ribbonek.gnu
rm -f    slabek.dat
rm -f    slabek.gnu
rm -f    slabek.png
rm -f    slabek2d-matlab.dat
rm -f    slabek2d.dat
rm -f    slabek_plane-matlab.dat
rm -f    slabek_plane.dat
rm -f    slabek_plane.gnu
rm -f    slabek_plane.png
rm -f    spindos.dat_l
rm -f    spindos.dat_r
rm -f    spintext_l.gnu
rm -f    spintext_l.png
rm -f    spintext_r.gnu
rm -f    surfdos_bulk.gnu
rm -f    surfdos_l.gnu
rm -f    surfdos_l_only.gnu
rm -f    surfdos_r.gnu
rm -f    surfdos_r_only.gnu
rm -f    wanniercenter3D_Z2.eps
rm -f    wanniercenter3D_Z2.gnu
rm -f    wanniercenter3D_Z2_1.dat
rm -f    wanniercenter3D_Z2_2.dat
rm -f    wanniercenter3D_Z2_3.dat
rm -f    wanniercenter3D_Z2_4.dat
rm -f    wanniercenter3D_Z2_5.dat
rm -f    wanniercenter3D_Z2_6.dat
rm -f    wcc.dat
rm -f    wcc.gnu
rm -f FS3D*
